name: Deploy Hugo Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Hugo Repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Hugo
        run: |
          HUGO_VERSION=$(curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | jq -r .tag_name | sed 's/^v//')
          wget -qO- https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz | tar -xz hugo
          sudo mv hugo /usr/local/bin/

      - name: Build and Deploy to GitHub Pages Repo
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          rm -rf public/

          git clone https://$GH_PAT@github.com/pratulmuthuraja/pratulmuthuraja.github.io.git public
          
          hugo --minify

          cd public/

          git add .
          git commit -m "Deploy Hugo site - $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin main

